# kind: Deployment
# apiVersion: apps/v1
# metadata:
#   name: helloworld
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: helloworld
#   template:
#     metadata:
#       labels:
#         app: helloworld
#     spec:
#       containers:
#         - name: helloworld
#           image: 'helloworld:latest'
#           imagePullPolicy: Never
#       restartPolicy: Always

