# kind: Deployment
# apiVersion: apps/v1
# metadata:
#   name: helloworld2
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: helloworld2
#   template:
#     metadata:
#       labels:
#         app: helloworld2
#     spec:
#       containers:
#         - name: helloworld2
#           image: 'pangliter/helloworld2'
#           imagePullPolicy: IfNotPresent
#       restartPolicy: Always

