kind: Service
apiVersion: v1
metadata:
  name: rollout-canary
  labels:
    app: rollout-canary
    id: rollout-canary
spec:
  ports:
  - port: 8080
  selector:
    app: rollout-canary
    id: rollout-canary
  type: LoadBalancer

