kind: Service
apiVersion: v1
metadata:
  name: helloworld
  namespace: default
  labels:
    app: helloworld
spec:
  ports:
    - name: webserver
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: helloworld
  type: ClusterIP
  sessionAffinity: None

